version: '3.8'

services:
  frontend:
    container_name: corona-frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 8080
  backend:
    container_name: corona-backend
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    expose:
      - 8080
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development