version: '3.8'

services:
  frontend:
    container_name: corona-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    expose:
      - 8080
    command: npm start
  backend:
    container_name: corona-backend
    restart: always
    build: ./backend
    command: python main.py run -h 0.0.0.0
    ports:
      - 5000:5000
    expose:
      - 8080
    environment:
      - FLASK_APP=api.py
      - FLASK_ENV=development